### ISSUE TITLE
Cannot be aware of changing fields in an update request.

### ISSUE THREAD

**Issue by ghost** [elegos/PHP-object-transmapper-validator#1]
Given a scenario like this:

    /**
     * @param Request $request
     * @param mixed $id
     * @return JsonResponse
     */
    public function updateAction(Request $request, $id)
    {
        $this->userRoleChecker
            ->checkPermission('LANGUAGE_UPDATE');

        $requestData = json_decode($request->getContent());

        $attributes = $requestData->data
            ->attributes;

        $language = $this->languageProvider
            ->find($attributes->id);

        if (null === $language) {
            return new JsonResponse(
                sprintf('Language not found %d not found', $attributes->id),
                Response::HTTP_NOT_FOUND
            );
        }

        if (isset($attributes->name)) {
            $this->languageUpdater
                ->setName($language, $attributes->name);
        }

        if (isset($attributes->nativeName)) {
            $this->languageUpdater
                ->setNativeName($language, $attributes->nativeName);
        }

        if (isset($attributes->countryCode)) {
            $this->languageUpdater
                ->setCountryCode($language, $attributes->countryCode);
        }

        return new JsonResponse(['id' => $language->getId()], Response::HTTP_OK);
    }

The php stdObject or the array allow me to do an isset.
Without adding any line of code to this example, (Except the one to validate the request payload), how will you allow user to know about fields to update or not?

How can I say eg. nativeName is missing so no update is needed?
Consider that if you return null, for me means set nativeName to null and not, nativeName is not to change.

**Comment by elegos** [comment]
I'd do something like this:

    use GiacomoFurlan\ObjectTransmapperValidator\Annotation\Validation\Validate

    class UpdateLanguageModel
    {
        /**
         * @var int
         * @Validate(type="int", mandatory=true)
         */
        private $id;

        /**
         * @var string|null
         * @Validate(type="string", mandatory=false)
         */
        private $name;

        /**
         * @var string|null
         * @Validate(type="string", mandatory=false)
         */
        private $nativeName;

        /**
         * @var string|null
         * @Validate(type="string", mandatory=false)
         */
        private $countryCode;

        /**
         * @return int
         */
        public function getId() : int
        {
            return $this->id;
        }

        /**
         * @return string|null
         */
        public function getName() : ?string
        {
            return $this->name;
        }

        /**
         * @return string|null
         */
        public function getNativeName() : ?string
        {
            return $this->nativeName;
        }

        /**
         * @return string|null
         */
        public function getCountryCode() : ?string
        {
            return $this->countryCode;
        }
    }

And following your class:

    /**
     * @param Request $request
     * @param mixed $id
     * @return JsonResponse
     */
    public function updateAction(Request $request, $id)
    {
        $this->userRoleChecker
            ->checkPermission('LANGUAGE_UPDATE');

        $requestData = json_decode($request->getContent());

        $attributes = $requestData->data
            ->attributes;

        // This may throw a ValidationException, or another exception as defined in the model class
        $updateModel = $this->transmapper->map($attributes, UpdateLanguageModel::class);

        $language = $this->languageProvider
            ->find($updateModel->getId());

        if (null === $language) {
            return new JsonResponse(
                sprintf('Language not found %d not found', $updateModel->getId()),
                Response::HTTP_NOT_FOUND
            );
        }

        if (null !== $updateModel->getName()) {
            $this->languageUpdater
                ->setName($language, $updateModel->getName());
        }

        if (null !== $updateModel->getNativeName()) {
            $this->languageUpdater
                ->setNativeName($language, $updateModel->getNativeName());
        }

        if (null !== $updateModel->getCountryCode()) {
            $this->languageUpdater
                ->setCountryCode($language, $updateModel->getCountryCode());
        }

        return new JsonResponse(['id' => $language->getId()], Response::HTTP_OK);
    }

Though at this point, having an UpdateModel, I'd rather do something like this with your controller, i.e. moving all the checks in the updater (which updates if not null), rather than letting the controller do the isset checks:

    /**
     * @param Request $request
     * @param mixed $id
     * @return JsonResponse
     */
    public function updateAction(Request $request, $id)
    {
        $this->userRoleChecker
            ->checkPermission('LANGUAGE_UPDATE');

        $requestData = json_decode($request->getContent());

        $attributes = $requestData->data
            ->attributes;

        // This may throw a ValidationException, or another exception as defined in the model class
        $updateModel = $this->transmapper->map($attributes, UpdateLanguageModel::class);

        $language = $this->languageProvider
            ->find($updateModel->getId());

        if (null === $language) {
            return new JsonResponse(
                sprintf('Language not found %d not found', $attributes->id),
                Response::HTTP_NOT_FOUND
            );
        }

        $this->languageUpdater->update($language, $updateModel);

        return new JsonResponse(['id' => $language->getId()], Response::HTTP_OK);
    }

**Comment by ghost** [comment]
ok va bene
ovviamente dove hai tralasciato $attributes->id doveva diventare $updateModel->getId()
